name: CI

on: push

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.6"
          - "2.7"
          - "3.0"
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: "2.4.7"
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake spec
